<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta http-equiv="X-UA-Compatible" content="IE=7" />
<title>后台首页</title>
<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl('static/css/style.css'); ?>" />
</head>
<body>
<div class="top_identity">
欢迎登录管理后台, <?php echo $this->identity; ?>&nbsp;
[<a href="<?php echo $this->url(array('action'=>'index', 'controller'=>'index', 'module'=>'demo')); ?>">DEMO首页</a>]
	&nbsp;[<a href="<?php echo $this->url(array('action'=>'index', 'controller'=>'logout', 'module'=>'auth')); ?>">退出登录</a>]
</div>
<h1>管理后台</h1>
<?php echo $this->render('menu.phtml'); ?>
<div class="main_content">
<?php
if ($this->messages) {
	foreach ($this->messages as $m) {
?>
	<p><?php echo $m; ?></p>
<?php
	}
}
?>
<?php echo $this->layout()->content ?>
</div>
</body>
</html>

