<form action="<?php echo $this->url(array('action'=>'saveadd')); ?>" method="post">
<table>
<tr>
<th>广告名称</th>
<td><input name="name"></td>
<td>广告的名称</td>
</tr>
<tr>
<th>广告图片</th>
<td><input name="image"></td>
<td>广告图片物料</td>
</tr>
<tr>
<th>链接地址</th>
<td><input name="url"></td>
<td>广告的链接地址</td>
</tr>

<tr>
<th>跟踪ID</th>
<td><input name="tracid"></td>
<td>跟踪广告用的，适用于谷歌流量统计</td>
</tr>

<tr>
<th>广告位</th>
<td><select name="zoneid">
<?php foreach ($this->adzone as $a):
?>
<option value="<?php echo $a['id']; ?>"><?php echo $a['name']; ?></option>
<?php endforeach; ?>
</select></td>
<td>广告投放的位置</td>
</tr>

<tr>
<th>上线时间</th>
<td><input name="uptime" value="<?php echo date('Y-m-d'); ?>"></td>
<td>广告上线的时间</td>
</tr>
<tr>
<th>下线时间</th>
<td><input name="downtime" value="<?php echo date('Y-m-d', strtotime('+1 days')); ?>"></td>
<td>广告下线时间</td>
</tr>
<tr>
<th>广告状态</th>
<td><select name="status">
<option value="-2"> 已拒绝</option>
<option value="-1"> 未审核</option>
<option value="0" selected="selected"> 正常</option>
<option value="1">已结束</option>
</select></td>
<td>广告状态</td>
</tr>
<tr>
<th></th>
<td><input type="submit" value="提交"></td>
<td></td>
</tr>
</table>
</form>
