<?php
if ($this->adzone) :
?>
<table>
<tr>
<th>广告位</th>
<th>宽度</th>
<th>高度</th>
<th>详情</th>
<th>操作</th>
</tr>

<?php
	foreach ($this->adzone as $a) :
?>
<tr>
<td><?php echo $a['name']; ?></td>
<td><?php echo $a['width']; ?></td>
<td><?php echo $a['height']; ?></td>
<td><?php echo $a['description']; ?></td>
<td><a href="<?php echo $this->url(array('action'=>'edit', 'id'=>$a['id'])); ?>">编辑</a>&nbsp;&nbsp;<a href="<?php echo $this->url(array('action'=>'delete', 'id'=>$a['id'])); ?>">删除</a></td>
</tr>
<?php
endforeach;
?>
</table>
<?php 
endif;
?>
