<?php
if ($this->adzone) :
?>
<p><a href="http://w.netroby.com/fastem_publish_adzone">FastEM 广告投放指导</a></p>
<table> 
<tr>
<th>头部代码</th>
<td>
<strong>包含google analytics统计代码</strong>
<br />
<textarea style="width:850px;height:72px;font-size:8px;border:#EEE 1px inset;"><script type="text/javascript">var _sl = new Array();var _gaq = _gaq || [];_gaq.push(['_setAccount', 'UA-4450773-12']);_gaq.push(['_setDomainName', '.netroby.com']);_gaq.push(['_trackPageview']);(function() { var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);})();</script></textarea>
<br />
<strong>不包含google analytics统计代码</strong>
<br />
<textarea style="width:850px;font-size:8px;height:12px;border:#EEE 1px inset;"><script type="text/javascript">var _sl = new Array();</script></textarea>
</td>
</tr>
<tr>
<th>body代码</th>
<td>
从下面一个表格中，获取body代码
</td>
</tr>
<tr>
<th>尾部代码</th>
<td>
<textarea style="width:850px;font-size:8px;height:48px;border:#EEE 1px inset"><script type="text/javascript">(function() {var _m = document.createElement('script'); _m.type = 'text/javascript'; _m.async = true;_m.src = 'http://<?php echo $this->server_name; ?>/?sl=' + _sl.toString();var _s = document.getElementsByTagName('script')[0]; _s.parentNode.insertBefore(_m, _s);})();</script></textarea>
</td> 
</tr>
</table>
<br />
<table>
<tr>
<th>广告位</th>
<th>宽度</th>
<th>高度</th>
<th>详情</th>
<th>广告代码</th>
<th>操作</th>
</tr>

<?php
	foreach ($this->adzone as $a) :
?>
<tr>
<td><?php echo $a['name']; ?></td>
<td><?php echo $a['width']; ?></td>
<td><?php echo $a['height']; ?></td>
<td><?php echo $a['description']; ?></td>
<td><textarea style="width:150px;height:64px;font-size:10px;"><div id="_sl_<?php echo $a['id']; ?>" style="margin:0px;padding:0px;border:0px;width:<?php echo $a['width']; ?>px;height:<?php echo $a['height']; ?>px"></div><script type="text/javascript">_sl.push(<?php echo $a['id']; ?>);</script></textarea></td>
<td><a href="<?php echo $this->url(array('action'=>'edit', 'id'=>$a['id'])); ?>">编辑</a>&nbsp;&nbsp;<a href="<?php echo $this->url(array('action'=>'delete', 'id'=>$a['id'])); ?>">删除</a></td>
</tr>
<?php
endforeach;
?>
</table>
<?php 
endif;
?>
