<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta http-equiv="X-UA-Compatible" content="IE=7" />
<title>FastEM Demon</title>
<script type="text/javascript">var _sl = new Array();
var _gaq = _gaq || [];
_gaq.push(['_setAccount', 'UA-4450773-12']);
_gaq.push(['_setDomainName', '.netroby.com']);
_gaq.push(['_trackPageview']);
(function() {
	var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
	ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
	var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
})();
</script>
</head>
<body>
<?php foreach ($this->adzone as $a) : ?>
<div id="_sl_<?php echo $a['id']; ?>" style="margin:0px;padding:0px;border:0px;width:<?php echo $a['width']; ?>px;height:<?php echo $a['height']; ?>px"></div>
<script type="text/javascript">_sl.push(<?php echo $a['id']; ?>);</script>
<?php endforeach; ?>
<script type="text/javascript">
(function() {
	var _m = document.createElement('script'); _m.type = 'text/javascript'; _m.async = true;
	_m.src = 'http://<?php echo $_SERVER['SERVER_NAME']; ?>/?sl=' + _sl.toString();
	var _s = document.getElementsByTagName('script')[0]; _s.parentNode.insertBefore(_m, _s);
})();
</script>
</body>
</html>

