<!DOCTYPE html>
<html>
	<head>
		<title>FastEM Demon</title>
<script>var _sl = new Array();
var _gaq = _gaq || [];
_gaq.push(['_setAccount', 'UA-4450773-12']);
_gaq.push(['_trackPageview']);
(function() {
	var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
	ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
	var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
})();
</script>
</head>
<body>
<div id="_sl_1"></div>
<script>_sl.push(1);</script>
<script>
(function() {
	var _m = document.createElement('script'); _m.type = 'text/javascript'; _m.async = true;
	_m.src = 'http://s.netroby.com/?sl=' + _sl.toString();

	var _s = document.getElementsByTagName('script')[0]; _s.parentNode.insertBefore(_m, _s);

})();
</script>
</body>
</html>

